### ISSUE TITLE
10093 is hardcoded

### ISSUE THREAD

**Issue by pe1rrr** [pfiliberti/tncemu#1]
Hi! Just been scrubbing my head why any port I defined other than 10093 was getting bind errors reporting address already in use (as it is, by BPQ). 

I'm no coder so I don't know how to make a commit for git but the issue is on line 264 of tnc.c where the port 10093 is hard baked instead of taking the parameter.

At least, thats how I figured it, 🤔

**Comment by pfiliberti** [comment]
Thats intersting I have never run it at same time as bpq instance. I will
make a change to allow a parameter for that as well….

**Comment by pfiliberti** [comment]
If your trying to talk to your bpq node with tnc line 264 of tnc.c is hard
coded to 10094
because of course 10093 may be used locally by bpq instance. I should
change this in
future to make it a parameter. To talk to your bpq node you need to have it
listen also
on 10094 since bpq always talked back on same port it has recvd traffic on.
So in
bpq config add :
UDP 10094              ;Also listen to 10094
After your UDP 10093 line. BPQ will listen to both.
When running tnc.c use the command line tnc -t BPQ_IP_ADDR(127.0.0.1) -p
10094

That will connect to your bpq node on 10094 and also listen for bpq to talk
back on 10094.

Let me know if that helps.

73
Peter

**Comment by pe1rrr** [comment]
```
  sin.sin_family=AF_INET;
	sin.sin_addr.s_addr=INADDR_ANY;
  if(!use_kiss) sin.sin_port=htons(10093);
```

It would be good to have this as a configurable parameter, for some nodes like mine we have a range of UDP ports open to accommodate special situations, in my case UDP listeners are on from 10093 to 10100, so 10094 would also trip over.


Not sure if the TNC's listener is working as intended, because I set the TNC's listening port to 10999 just to get rid of the binding error. A funny thing happened where the node could connect to the TNC back over the same UDP connection that the TNC initiated to the node, which was weird and probably not intentional.

Where 11 is my AXIP port on rrrnet:

```
c 11 pe1rrr
RRRNET:PE1RRR-5} Connected to PE1RRR
Welcome! This is a virtual TNC! I may not be here, if not pls leave msg on bbs. 73
```

**Comment by pfiliberti** [comment]
It was intentional for the tnc to accept connections back from the node. I
use the tnc
as my msg node in my house, it is connected to the bpq node in my shack. I
setup
aliases on bpq for kf7psm and kf7psm-1 to forward to my tncemu node here in
the
house. That way if someone trys to connect to kf7psm-1 on the local vhf
port bpq
will answer and forward to tncemu where they can leave a msg on the tnc's
pbbs.
That way I don't have to run a full bbs on bpq and also if they connect to
kf7psm
they get my keyboard chat on the tncemu.

73

**Comment by pfiliberti** [comment]
Some notes on how I use tncemu with bpq.
In my bpq config I have the following:
MAP KF7PSM IPOFTNCEMU UDP 10094 B
MAP KF7PSM-1 IPOFTNCEMU UDP 10094 B
APPLICATION 1,PBBS,C 1 KF7PSM-1,KF7PSM-1
APPLICATION 2,MYTNC,C 1 KF7PSM,KF7PSM

**Comment by pfiliberti** [comment]
RIP Red PE1RRR SK
